### ISSUE TITLE
Remove old files

### ISSUE THREAD

**Issue by tbaudier** [OpenSyd/syd#1]
This files seem to be unnecessary:
 - syd/syd_faf_calibration.py
 - syd/syd_itk_attenuation_coefficient_factor_image.py
 - syd/syd_itk_crop_planar.py
 - syd/syd_itk_flip_image.py
 - syd/syd_itk_geometrical_mean.py 
 - syd/syd_itk_projection_image.py
 - syd/syd_itk_register_planar_images.py

**Comment by dsarrut** [comment]
sure, go!
